### ISSUE TITLE
健康診断結果報告書と特定保健指導の比較

### ISSUE THREAD

**Issue by hosanai** [HealthDataWorks/fhir-ig-jp-specific-health-guidance#3]
健康診断結果報告書と特定保健指導の比較整理、また、内容についての議論をまとめた資料を添付します。この内容で実装ガイドの修正を実施しましょう。
[健康診断結果報告書と特定保健指導のFHIRリソース比較.xlsx](https://github.com/HealthDataWorks/fhir-ig-jp-specific-health-guidance/files/6592052/FHIR.xlsx)

**Comment by ns0602yk** [comment]
資料 健康診断結果報告書と特定保健指導のFHIRリソース比較.xlsx の内容にしたがって実装ガイドを修正しました
